### ISSUE TITLE
Own contact formular

### ISSUE THREAD

**Issue by rugk** [desec-io/desec-static#1]
Currently you rely on https://encrypt.to as a contact formular.
This has the disadvantage that users have to trust your encrypt.to. Also the design does not fit well... :wink: 

So maybe it would be a good idea to create an encrypted contact form by yourself. It is not so hard AFAIK.
Here is a tutorial: https://scotthelme.co.uk/creating-a-pgp-contact-form/

**Comment by peterthomassen** [comment]
Thank you for this very neat suggestion. I agree with you that the design does not fit well, and requiring to trust an external site is not good either.

Would you mind creating a pull request for this? It should not be too difficult if you've used npm and bower before. OpenPGP.js should be available through npm, so no need to keep separate code around.

On this occasion, let me also say that I'm very happy that people care about what we do, and start suggesting improvement. Thanks a lot!

**Comment by rugk** [comment]
> It should not be too difficult if you've used npm and bower before

I have not used them so much. Maybe I'll look into it in the future, but for now I'd encourage other contributors to look into this.

> On this occasion, let me also say that I'm very happy that people care about what we do, and start suggesting improvement.

Oh yeah I do. :smiley:

**Comment by peterthomassen** [comment]
not needed, so relaunched web site without contact form
