### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [desec-io/desec-static#2]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
* And here is how you can sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by peterthomassen** [comment]
This issue is not about the code in this repository, so I'm closing this. However, we'll consider signing code for future commits.

**Comment by rugk** [comment]
That's nice. Indeed I did not know where to open it, so I just opened one here.

**Comment by peterthomassen** [comment]
https://mikegerwitz.com/papers/git-horror-story has some nice thoughts on this topic

**Comment by rugk** [comment]
Yes and I already linked some information on how to do it properly, so that this horror story does not happen.
So you finally sign commits?

**Comment by peterthomassen** [comment]
As my previous comment indicates, we're evaluating which security / signing policy to adopt.

**Comment by rugk** [comment]
Okay
